[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ---> REQUIRED FOR YOUR 650KB SOUNDFONT <---
board_build.partitions = huge_app.csv

; Deep scan required for the Audio library
lib_ldf_mode = deep

lib_deps = 
    fastled/FastLED @ ^3.10.3
    adafruit/RTClib @ ^2.1.4
    
    ; Your existing audio library (great for MP3s/WAVs)
    esphome/ESP32-audioI2S @ ^2.3.0
    
    ; The new library required for raw TSF buffer streaming
    https://github.com/pschatzmann/arduino-audio-tools.git